export type Review = {
  id: string;
  name: string;
  handle: string;
  verified: boolean;
  avatar: string;
  text: string;
  replyingTo: string[];
  date: string;
  likes: number;
  replies: number;
};

export const reviews: Review[] = [
  {
    id: "2027436735261503832",
    name: "Vladimir Deev",
    handle: "vdeev7",
    verified: false,
    avatar: "/images/reviews/vdeev7.jpg",
    text: "Absolutely love it, thank you very much, Toby, for great job!",
    replyingTo: ["@TobyBelhome"],
    date: "5:32 PM · Feb 27, 2026",
    likes: 1,
    replies: 1,
  },
  {
    id: "1928222392783872187",
    name: "Daniel Humphreys",
    handle: "alias_labs_",
    verified: false,
    avatar: "/images/reviews/alias_labs_.png",
    text: "🫡🫡 legend!\nLove the kit bro, thanks for constantly delivering!",
    replyingTo: ["@TobyBelhome", "@shadcn"],
    date: "10:50 PM · May 29, 2025",
    likes: 1,
    replies: 1,
  },
  {
    id: "2027682374054809667",
    name: "SHARIAR",
    handle: "shariar_design",
    verified: true,
    avatar: "/images/reviews/shariar_design.jpg",
    text: "Next level work bro🔥 keep going.",
    replyingTo: ["@TobyBelhome"],
    date: "9:48 AM · Feb 28, 2026",
    likes: 0,
    replies: 0,
  },
  {
    id: "1997525718691958853",
    name: "Marshall",
    handle: "mdnlabs",
    verified: true,
    avatar: "/images/reviews/mdnlabs.jpg",
    text: "First time seeing this product... Couldn't believe my eyes. I bought within 5 minutes. Thank you for providing this.",
    replyingTo: ["@TobyBelhome"],
    date: "4:36 AM · Dec 7, 2025",
    likes: 2,
    replies: 1,
  },
  {
    id: "1997468057724420205",
    name: "Mohamed Kondombo",
    handle: "mkmastery99",
    verified: false,
    avatar: "/images/reviews/mkmastery99.jpg",
    text: "The work you do is really great. Quality work 🥰🥰🥰",
    replyingTo: ["@TobyBelhome"],
    date: "12:47 AM · Dec 7, 2025",
    likes: 2,
    replies: 1,
  },
  {
    id: "1997563029886837198",
    name: "Kevin Usadadiya",
    handle: "Kevin_Usadadiya",
    verified: false,
    avatar: "/images/reviews/kevin_usadadiya.jpg",
    text: "I just discovered you from one of my colleague, great work.",
    replyingTo: ["@TobyBelhome"],
    date: "7:05 AM · Dec 7, 2025",
    likes: 1,
    replies: 1,
  },
  {
    id: "1911988450200268993",
    name: "VEERA SRIVASTAVA | UI/UX DESIGN COACH",
    handle: "VeeraSrivastava",
    verified: true,
    avatar: "/images/reviews/veerasrivastava.jpg",
    text: "Your dashboard hit the sweet spot 🎯 between helpful and magnificent.",
    replyingTo: ["@TobyBelhome", "@shadcn"],
    date: "3:42 AM · Apr 15, 2025",
    likes: 2,
    replies: 0,
  },
  {
    id: "1902357260459757643",
    name: "Nima",
    handle: "Nimmortal7",
    verified: false,
    avatar: "/images/reviews/nimmortal7.png",
    text: "Great work 🔥",
    replyingTo: ["@TobyBelhome", "@shadcn"],
    date: "1:51 PM · Mar 19, 2025",
    likes: 1,
    replies: 1,
  },
  {
    id: "1865378176194552272",
    name: "Alejandro Martinez",
    handle: "lyricalstring",
    verified: false,
    avatar: "/images/reviews/lyricalstring.jpg",
    text: "I use the shadcn ui kit pretty often and it's crazy what people build with it, good job 👏🏻",
    replyingTo: ["@TobyBelhome", "@shadcn"],
    date: "12:49 PM · Dec 7, 2024",
    likes: 0,
    replies: 0,
  },
  {
    id: "1865343459055255752",
    name: "Saïd Aitmbarek",
    handle: "SaidAitmbarek",
    verified: true,
    avatar: "/images/reviews/saidaitmbarek.jpg",
    text: "looks really clean ;)",
    replyingTo: ["@TobyBelhome", "@shadcn"],
    date: "10:31 AM · Dec 7, 2024",
    likes: 1,
    replies: 1,
  },
  {
    id: "1897606813689782331",
    name: "Sadman Shakib",
    handle: "drsadmanshakib",
    verified: false,
    avatar: "/images/reviews/drsadmanshakib.jpg",
    text: "Wow looks really cool",
    replyingTo: ["@TobyBelhome", "@shadcn"],
    date: "11:14 AM · Mar 6, 2025",
    likes: 0,
    replies: 0,
  },
  {
    id: "1897645378285011287",
    name: "Flo",
    handle: "Flo_oskar",
    verified: true,
    avatar: "/images/reviews/flo_oskar.jpg",
    text: "Uff exactly what I was looking for in shadcn",
    replyingTo: ["@TobyBelhome", "@shadcn"],
    date: "1:48 PM · Mar 6, 2025",
    likes: 1,
    replies: 0,
  },
  {
    id: "1920944941695463567",
    name: "Elijah||Software Engineer",
    handle: "ElijahNdenwa1",
    verified: false,
    avatar: "/images/reviews/elijahndenwa1.jpg",
    text: "This looks neat.",
    replyingTo: ["@TobyBelhome", "@shadcn"],
    date: "8:52 PM · May 9, 2025",
    likes: 0,
    replies: 0,
  },
  {
    id: "1908718152252284983",
    name: "alex.xyz",
    handle: "alex___xyz",
    verified: true,
    avatar: "/images/reviews/alex___xyz.jpg",
    text: "Sleek UI, mate! Loving the design vibes! 👀",
    replyingTo: ["@TobyBelhome", "@shadcn"],
    date: "3:07 AM · Apr 6, 2025",
    likes: 1,
    replies: 0,
  },
  {
    id: "1919547360503366055",
    name: "Sarim Malik",
    handle: "sarimrmalik",
    verified: true,
    avatar: "/images/reviews/sarimrmalik.jpg",
    text: "The examples on your website are so good",
    replyingTo: ["@TobyBelhome", "@shadcn"],
    date: "12:18 AM · May 6, 2025",
    likes: 2,
    replies: 0,
  },
];
